POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pcm9iIiwiaWQiOiI2MDgxYzgxMThjOGM0ZTQzMTQ1ZjA5MTEiLCJpYXQiOjE2MTkxNTI5NzF9.hhJqvcSLEmwh67ip9DBb-frN0fPrwE6ddLnVd9ncssk

{  
    "title": "Valid user's post next day post",
    "author": "author",
    "url": "http://dummy.com",
    "likes": 2,
    "userId": "60813a7de4012f46ecaf646e"
}